django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

post/urls.py
from django.urls import path

from . import views


app_name = 'post'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path(
        '<int:year>/<int:month>/<int:day>/<str:slug>',
        views.post_detail,
        name='post_detail'
    ),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/<str:slug>', views.post_detail, name='post_detail'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='published')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse(
            'post:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    username = models.CharField(max_length=120)
    email = models.EmailField(blank=True, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.username, self.post)

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ("-publish", )

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("posts:post_detail", args=[self.id, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=120)
    email = models.EmailField(blank=True, null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("-created", )

    def __str__(self):
        return "Comment by {} on {}".format(self.name, self.post)

posts/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

post/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag

from .models import Post
from .forms import CommentForm


def post_list(request, tag_slug=None):
    if tag_slug:
        tag = Tag.objects.filter(slug=tag_slug).first()
        all_posts = Post.objects.filter(tags__in=[tag])
    else:
        all_posts = Post.objects.all()
    tag_list = Tag.objects.all()
    paginator = Paginator(all_posts, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'post/list.html',
        {
            'posts': posts,
            'tag_list': tag_list
        }
    )


def post_detail(request, year, month, day, slug):
    post = Post.objects.filter(
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug
    ).first()
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect('post:post_detail', year=year, month=month, day=day, slug=slug)
    else:
        comment_form = CommentForm()
    tag_list = Tag.objects.all()

    return render(
        request,
        'post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'tag_list': tag_list,
        }
    )

posts/views.py
import markdown
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from taggit.models import Tag

from .forms import CommentForm
from .models import Post


def post_list(request, tag_slug=None):
    tag = None
    if tag_slug:
        tag = Tag.objects.filter(slug=tag_slug).first()
        all_posts = Post.objects.filter(tags__in=[tag])
    else:
        all_posts = Post.objects.all()
    tag_list = Tag.objects.all()
    paginator = Paginator(all_posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'tag_list': tag_list,
        'tag_slug': tag_slug,
        'tag': tag,
    }

    return render(request, 'blog/posts/list.html', context)


def post_detail(request, id, slug):
    posts = Post.objects.filter(
        id=id,
        slug=slug,
    ).first()

    markdown_extensions = [
        'markdown.extensions.extra',
        'markdown.extensions.abbr',
        'markdown.extensions.attr_list',
        'markdown.extensions.def_list',
        'markdown.extensions.fenced_code',
        'markdown.extensions.footnotes',
        'markdown.extensions.md_in_html',
        'markdown.extensions.tables',
        'markdown.extensions.admonition',
        'markdown.extensions.codehilite',
        'markdown.extensions.legacy_attrs',
        'markdown.extensions.legacy_em',
        'markdown.extensions.meta',
        'markdown.extensions.nl2br',
        'markdown.extensions.sane_lists',
        'markdown.extensions.smarty',
        'markdown.extensions.toc',
        'markdown.extensions.wikilinks',
    ]

    posts.body = markdown.markdown(posts.body, extensions=markdown_extensions)

    comments = posts.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
            return redirect('posts:post_detail', id=id, slug=slug)
    else:
        comment_form = CommentForm()
    tag_list = Tag.objects.all()

    context = {
        'posts': posts,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'tag_list': tag_list,
    }

    return render(request, 'blog/posts/detail.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Highlight -->
    <link rel="stylesheet" href="{% static "css/highlights_github.css" %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "img/site.webmanifest" %}">

    <!-- Title -->
    <title>{% block title %}{% endblock %} | Blog</title>
</head>

<body class="d-flex flex-column h-100">

<!-- Navbar -->
{% include 'partials/navbar.html' %}

<!-- Main -->
<main class="container">
    <div class="row">
        <!-- Main content-->
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
        <!-- Sidebar -->
        <div class="col-md-4 text-center">
            {% include 'partials/sidebar.html' %}
        </div>
    </div>
</main>

<!-- Footer -->
{% include 'partials/footer.html' %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static "js/jquery-3.5.1.slim.min.js" %}"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

templates/blog/partials/footer.html
{% load static %}

<footer class="footer mt-auto pt-5 pb-4 bg-white text-center">
  <div class="container">
    <small
      >&copy; <a href="mailto:me.xinyuwen@gmail.com">Xinyu Wen</a>. All rights reserved.
    </small>
  </div>
</footer>

templates/blog/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom py-2">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:post_list" %}">BLOG</a>
  </div>
</nav>

templates/blog/partials/sidebar.html
{% load static %}

<div class="jumbotron border bg-white pt-4 mt-5 mx-4 px-2">
    <div class="h2 mb-4">Tags</div>
    <hr>
    <div class="container my-3">
        {% for tag in tag_list %}
            <a class="btn btn-outline-primary font-italic my-1 mx-1"
               href="{% url "posts:post_list_by_tag" tag.slug %}">{{ tag.name }}
                <span class="badge badge-secondary">{{ tag.taggit_taggeditem_items.count }}</span>
            </a>
        {% endfor %}
    </div>
</div>

templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block content %}

    <div>
        <h3 style="margin-bottom: 20px;"><a class="text-decoration-none text-dark"
                                            href="{{ post.get_url }}">{{ post.title }}</a>
        </h3>

        <div style="margin-bottom: 30px;">
            <small class="font-italic">Posted by
                <code>{{ post.author }}</code>
                <span class="flask-moment"> on {{ post.publish }}</span>
                {% if post.tags.count %}
                    Tags
                    {% for tag in post.tags.all %}
                        <a href="{% url "post:post_list_by_tag" tag.slug %}"
                           class="badge badge-primary text-white text-decoration-none">{{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
            </small>
        </div>

        <div class="font-weight-light">{{ post.body|linebreaks }}
        </div>

        <hr>

        <h4>Similar posts</h4>
        {% for post in post.tags.similar_objects %}
            <div class="font-weight-light">
                <a class="text-decoration-none" href="{{ post.get_url }}">{{ post.title }}</a>
            </div>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}

        <hr>

        {% with comments.count as total_comments %}
            <h4>{{ total_comments }}
                comment{{ total_comments|pluralize }}
            </h4>
        {% endwith %}

        <div style="margin-top: 20px;">
            {% for comment in comments %}
                <small class="font-italic">
                    <span class="badge badge-warning">#{{ forloop.counter }}</span>
                    <code>{{ comment.username }}</code>
                    {{ comment.created }}
                </small>
                <div class="font-weight-light" style="margin-top: 10px; margin-bottom: 10px;">
                    {{ comment.body }}
                </div>
            {% empty %}
                <div>There are no comments yet.</div>
            {% endfor %}

            <hr>

            {% if new_comment %}
                <h3>Your comment has been added!</h3>
            {% else %}
                <h3>Leave a Comment</h3>
                <form method="post">
                <div class="form-group">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" value="Add comment"></p>
                </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block content %}


    <div>
        <!-- Blog list -->
        {% for post in posts %}
            <h3 style="margin-bottom: 20px;">
                <a class="text-decoration-none text-dark"
                   href="{{ post.get_url }}">{{ post.title }}</a>
            </h3>

            <div style="margin-bottom: 30px;">
                <small class="font-italic">Posted by
                    <code>{{ post.author }}</code>
                    <span class="flask-moment"> on {{ post.publish }}</span>
                    {% if post.tags.count %}
                        Tags
                        {% for tag in post.tags.all %}
                            <a href="{% url "post:post_list_by_tag" tag.slug %}"
                               class="badge badge-primary text-white text-decoration-none">{{ tag.name }}</a>
                        {% endfor %}
                    {% endif %}
                </small>
            </div>

            <div class="font-weight-light">
                <p> {{ post.body|truncatewords:50|linebreaks }}</p>
            </div>

            <small class="font-italic"><a class="text-decoration-none" href="{{ post.get_url }}">Read
                more...</a></small>

            <hr>
        {% endfor %}

        <!-- Page change button -->
        <nav style="text-align: center">
            {% if posts.has_previous %}
                <a class="btn btn-outline-primary" href="?page={{ posts.previous_page_number }}">Previous</a>
            {% else %}
                <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            {% endif %}

            {% if posts.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ posts.next_page_number }}">Next</a>
            {% else %}
                <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1"
                   aria-disabled="true">Next</a>
            {% endif %}
        </nav>
    </div>

{% endblock %}

templates/blog/posts/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ posts.title }} | {% endblock %}

{% block content %}

    <div class="my-5">
        <!-- Post title -->
        <div>
            <h2 class="text-dark">{{ posts.title }}</h2>
        </div>
        <div class="mt-2">
            <small class="font-italic text-secondary">Posted by
                <code>{{ posts.author }}</code>
                <span> on {{ posts.publish }}</span>
                {% if posts.tags.count %}
                    Tags
                    {% for tag in posts.tags.all %}
                        <a href="{% url "posts:post_list_by_tag" tag.slug %}"
                           class="badge badge-primary text-white text-decoration-none p-1">{{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
            </small>
        </div>
        <hr class="my-5">

        <!-- Post body -->
        <p>{{ posts.body|safe|linebreaks }}</p>
        <hr class="mt-5">

        <!-- Similar posts -->
        <div class="mt-5">
            <h4>Similar posts</h4>
            {% for post in posts.tags.similar_objects %}
                <div>
                    <a href="{{ post.get_url }}">{{ post.title }}</a>
                </div>
            {% empty %}
                <p class="text-secondary font-italic">There are no similar posts yet.</p>
            {% endfor %}
        </div>

        <!-- Comment list -->
        <div class="mt-5">
            <h4>Comments ({{ comments.count }})</h4>
            {% for comment in comments %}
                <small class="font-italic">
                    <span class="badge badge-warning">#{{ forloop.counter }}</span>
                    <code>{{ comment.username }}</code>
                    {{ comment.created }}
                </small>
                <div class="my-1">
                    {{ comment.body }}
                </div>
            {% empty %}
                <p class="text-secondary font-italic">There are no comments yet.</p>
            {% endfor %}
        </div>

        <!-- Comment form -->
        <div class="mt-5 col-md-8 pl-0">
            <h4 class="mb-4">Submit a new comment</h4>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {#                    <label for="name">Your Name</label>#}
                    <input type="text" name="name" id="name" class="form-control" placeholder="Name" required>
                </div>
                <div class="form-group">
                    {#                    <label for="email">Email</label>#}
                    <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                </div>
                <div class="form-group">
                    {#                    <label for="comment">Comment</label>#}
                    <textarea name="body" id="comment" class="form-control" rows="6" placeholder="Comment"
                              required></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/posts/list.html
{% extends "blog/base.html" %}

{% block title %}{% endblock %}

{% block content %}

    <div>
        <!-- Tag -->
        {% if tag_slug %}
            <div class="mt-4">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "posts:post_list" %}">All</a></li>
                        <li class="breadcrumb-item">{{ tag_slug|title }}</li>
                        <li class="ml-auto font-weight-light font-italic">
                            {{ tag.taggit_taggeditem_items.count }}
                            post{{ tag.taggit_taggeditem_items.count|pluralize }}</li>
                    </ol>
                </nav>
            </div>
        {% endif %}

        <!-- Blog list -->
        <div>
            {% for post in posts %}
                <h3 class="mt-5">
                    <a class="text-dark text-decoration-none" href="{{ post.get_url }}">{{ post.title }}</a>
                </h3>

                <div class="mt-3 mb-5">
                    <small class="font-italic text-secondary">Posted by
                        <code>{{ post.author }}</code>
                        <span> on {{ post.publish }}</span>
                        {% if post.tags.count %}
                            Tags
                            {% for tag in post.tags.all %}
                                <a href="{% url "posts:post_list_by_tag" tag.slug %}"
                                   class="badge badge-primary text-white text-decoration-none p-1">
                                    {{ tag.name }}</a>
                            {% endfor %}
                        {% endif %}
                    </small>
                </div>

                <!-- <div><p>{{ post.body|truncatewords:50|linebreaks }}</p></div>

                <div><a class="font-italic small mt-4" href="{{ post.get_url }}">Read more...</a></div> -->

            {% endfor %}
        </div>

        <!-- Pagination -->
        <nav class="my-5">
            <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo; Previous</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Previous</a></li>
                {% endif %}
                <li class="page-item disabled">
                    <span class="page-link text-dark">
                        {{ posts.number }} / {{ posts.paginator.num_pages }}</span></li>
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">Next &raquo;</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>

{% endblock %}

templates/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <div>
        <!-- Post title -->
        <h3><a class="text-decoration-none text-dark"
               href="{{ post.get_url }}">{{ post.title }}</a>
        </h3>

        <div>
            <small class="font-italic">Posted by
                <code>{{ post.author }}</code>
                <span class="flask-moment"> on {{ post.publish }}</span>
                {% if post.tags.count %}
                    Tags
                    {% for tag in post.tags.all %}
                        <a href="{% url "post:post_list_by_tag" tag.slug %}"
                           class="badge badge-primary text-white text-decoration-none p-1">{{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
            </small>
        </div>

        <!-- Post body -->
        <div class="font-weight-light">
            <p>{{ post.body|linebreaks }}</p>
        </div>
        <hr class="my-5">

        <!-- Similar posts -->
        <div class="my-3">
            <h4>Similar posts</h4>
            {% for post in post.tags.similar_objects %}
                <div class="font-weight-light">
                    <a class="text-decoration-none" href="{{ post.get_url }}">{{ post.title }}</a>
                </div>
            {% empty %}
                <p class="text-secondary font-italic font-weight-light">There are no similar posts yet.</p>
            {% endfor %}
        </div>

        <!-- Comment list -->
        <div class="my-5">
            <h4>Comments</h4>
            {% for comment in comments %}
                <small class="font-italic">
                    <span class="badge badge-warning">#{{ forloop.counter }}</span>
                    <code>{{ comment.username }}</code>
                    {{ comment.created }}
                </small>
                <div class="font-weight-light my-1">
                    {{ comment.body }}
                </div>
            {% empty %}
                <p class="text-secondary font-italic font-weight-light">There are no comments yet.</p>
            {% endfor %}
        </div>

        <!-- Comment form -->
        <div class="my-5">
            <h4 class="mb-3">New comment</h4>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea name="body" id="comment" class="form-control" rows="6" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-3">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/post/list.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

    <div>
        <!-- Blog list -->
        {% for post in posts %}
            <h3>
                <a class="text-decoration-none text-dark"
                   href="{{ post.get_url }}">{{ post.title }}</a>
            </h3>

            <div>
                <small class="font-italic">Posted by
                    <code>{{ post.author }}</code>
                    <span class="flask-moment"> on {{ post.publish }}</span>
                    {% if post.tags.count %}
                        Tags
                        {% for tag in post.tags.all %}
                            <a href="{% url "post:post_list_by_tag" tag.slug %}"
                               class="badge badge-primary text-white text-decoration-none p-1">{{ tag.name }}</a>
                        {% endfor %}
                    {% endif %}
                </small>
            </div>

            <div class="font-weight-light">
                <p> {{ post.body|truncatewords:50|linebreaks }}</p>
            </div>

            <div class="mb-4">
                <small class="font-italic"><a class="text-decoration-none" href="{{ post.get_url }}">Read
                    more...</a></small>
            </div>

        {% endfor %}

        <!-- Pagination -->
        <nav class="py-3">
            <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo; Previous</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Previous</a></li>
                {% endif %}
                <li class="page-item disabled">
                    <span class="page-link text-dark">
                        {{ posts.number }} / {{ posts.paginator.num_pages }}</span></li>
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">Next &raquo;</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>

{% endblock %}

templates/posts/list.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <div>
        <!-- Tag -->
        {% if tag_slug %}
            <div class="mt-4">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "posts:post_list" %}">All</a></li>
                        <li class="breadcrumb-item">{{ tag_slug|title }}</li>
                        <li class="ml-auto font-weight-light font-italic">
                            {{ tag.taggit_taggeditem_items.count }}
                            post{{ tag.taggit_taggeditem_items.count|pluralize }}</li>
                    </ol>
                </nav>
            </div>
        {% endif %}

        <!-- Blog list -->
        <div>
            {% for post in posts %}
                <h3 class="mt-5">
                    <a class="text-dark text-decoration-none" href="{{ post.get_url }}">{{ post.title }}</a>
                </h3>

                <div class="mt-3">
                    <small class="font-italic text-secondary">Posted by
                        <code>{{ post.author }}</code>
                        <span> on {{ post.publish }}</span>
                        {% if post.tags.count %}
                            Tags
                            {% for tag in post.tags.all %}
                                <a href="{% url "posts:post_list_by_tag" tag.slug %}"
                                   class="badge badge-primary text-white text-decoration-none p-1">
                                    {{ tag.name }}</a>
                            {% endfor %}
                        {% endif %}
                    </small>
                </div>

                {#                <div><p> {{ post.body|truncatewords:50|linebreaks }}</p></div>#}

                <div><a class="font-italic small mt-4" href="{{ post.get_url }}">Read more...</a></div>

            {% endfor %}
        </div>

        <!-- Pagination -->
        <nav class="my-5">
            <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo; Previous</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Previous</a></li>
                {% endif %}
                <li class="page-item disabled">
                    <span class="page-link text-dark">
                        {{ posts.number }} / {{ posts.paginator.num_pages }}</span></li>
                {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ posts.next_page_number }}">Next &raquo;</a></li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>

{% endblock %}